# Generated by Django 5.1.6 on 2025-03-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_sell_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sell_register",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
