# Generated by Django 5.1.6 on 2025-03-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
    ]
